### ISSUE TITLE
status doesn't have colors

### ISSUE THREAD

**Issue by alin-simionoiuDE** [tkrajina/multi-git#2]
i wonder if this is a simple fix, when i run 
# git multi status

the output doesn't come "colored" like it normally comes from me when i run git status on a repo. i have set globally color.status = auto

**Comment by tkrajina** [comment]
Hi, 

I did a quick search for this and found:

http://stackoverflow.com/questions/13299550/preserve-colored-output-from-python-os-popen

And this one:

http://bytes.com/topic/python/answers/541329-preserving-color-ouput-shell-command-via-os-popen

It seems the problems is that git commands are not aware that the python shell (or environment) is a color terminal, and git then don't send color characters to python. 

Other commands seems OK. For example, I tried this:

```
>>> import os
>>> a = os.popen("git status")
>>> print a.read()
# On branch private-tracks
# Untracked files:
#   (use "git add <file>..." to include in what will be committed)
#
#   aaa
nothing added to commit but untracked files present (use "git add" to track)

>>> a = os.popen("ls --color /")
>>> print a.read()
bin
boot
...
>>> 
```

With popen-ing "git status" I got no colors, but with "ls --color" the color characters are there. 

So, from this it seems the answer is -- it isn't possible :(
